[package]
name = "venice"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "3.2.17", features = ["derive"] }
lazy_static = "1.4.0"

[dev-dependencies]
insta = { version = "1.19.0", features = ["yaml"] }
