#!/bin/bash

set -eu

main() {
  input_path=$1
  object_path=${input_path/%.s/.o}
  output_path=${input_path%.s}

  nasm -f elf64 -o "$object_path" "$input_path"
  ld -dynamic-linker /lib64/ld-linux-x86-64.so.2 -o "$output_path" -lc "$object_path"
}

main "$@"
