#!/usr/bin/env python3
import glob
import subprocess
import sys


def main():
    failures = 0

    # Expected to pass.
    for path in glob.glob("samples/*.vn") + glob.glob("samples/typecheck/good/*.vn"):
        print(path)
        result = subprocess.run(
            ["./v.py", path], stdout=subprocess.PIPE, stderr=subprocess.PIPE
        )
        if result.returncode != 0:
            failures += 1
            print("  FAILURE!")

    # Expected to fail.
    for path in glob.iglob("samples/typecheck/bad/*.vn"):
        print(path)
        result = subprocess.run(
            ["./v.py", path], stdout=subprocess.PIPE, stderr=subprocess.PIPE
        )
        if result.returncode == 0:
            failures += 1
            print("  FAILURE! Expected the program not to type-check.")

    print()
    if failures > 0:
        print(f"Tests FAILED: {failures} failure(s)!")
        sys.exit(1)
    else:
        print("Tests passed.")
        sys.exit(0)


if __name__ == "__main__":
    main()
