#!/bin/bash
# Copyright 2022 The Venice Authors. All rights reserved.
# Use of this source code is governed by an MIT-style license that can be
# found in the LICENSE file.
#
# Compile a Venice program with debugging information.

set -eu

main() {
  cargo rustc -- -Awarnings  # -Awarnings suppresses warnings, which generate a lot of output.
  ./target/debug/venice --debug --keep-intermediate "$@"
}

main "$@"
